### ISSUE TITLE
每次都同步到 2018-06-30 程序就退出了

### ISSUE THREAD

**Issue by mirror222** [superoneio/eos_sql_db_plugin#3]
2534336ms thread-0   chain_plugin.cpp:853          log_guard_exception  ] Database has reached an unsafe level of usage, shutting down to avoid corrupting the database.  Please increase the value $
2534336ms thread-0   chain_plugin.cpp:859          log_guard_exception  ] Details: 3060101 database_guard_exception: Database usage is at unsafe levels
database free: 134209840, guard size: 134217728
    {"f":134209840,"g":134217728}
    thread-0  controller.cpp:1623 validate_db_available_size
2534336ms thread-0   net_plugin.cpp:3076           plugin_shutdown      ] shutdown..

**Comment by qq1032246642** [comment]
![image](https://user-images.githubusercontent.com/14926995/43564734-77651e0c-965a-11e8-8296-d68ad7d38ee6.png)
把这2个参数设大点

**Comment by mirror222** [comment]
谢谢。我试试
