### ISSUE TITLE
 Data loss when data synchronization

### ISSUE THREAD

**Issue by lovepluskaka** [superoneio/eos_sql_db_plugin#7]
The data of actions is synced to 9.20, but some data is missing.
Such as the actions of account iamthemangqi 
![](http://test.public.bitzhidao.com/EOSPNG.png)
The data form 9.1 to 9.20 is lost. 
![](http://test.public.bitzhidao.com/EOS-TRANSFORM.png)

**Comment by firesWu** [comment]
what version do you use? I can find it in my mysql.

![image](https://user-images.githubusercontent.com/14926995/45829450-89549580-bd2d-11e8-90b7-906775e20201.png)

**Comment by dbarobin** [comment]
Please describe the version of sql_db_plugin and re-open this issue.
